### ISSUE TITLE
nccl-tests/build/all_reduce_perf: undefined symbol: ncclRedOpCreatePreMulSum

### ISSUE THREAD

**Issue by sshleifer** [microsoft/msccl#16]
I followed the instructions in the README, but when it got time to run nccl tests I get the following error on an ndv4 node in azure:
### Command
```bash
mpirun -np 8 -mca pml ob1 --mca btl ^openib -mca btl_tcp_if_exclude lo,docker0 -mca  coll_hcoll_enable 0  -x LD_LIBRARY_PATH=msccl/build/lib/:$LD_LIBRARY_PATH \
  -x NCCL_DEBUG=INFO -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_NET_SHARED_BUFFERS=0 -x SCCL_XML_FILES=msccl/src/xml_generator/ar_ll.xml:msccl/src/xml_generator/ar_ll128.xml -x NCCL_ALGO=SCCL,RING,TREE -x CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7  \
    nccl-tests/build/all_reduce_perf -b 128 -e 64MB -f 2 -g 1 -c 1 -n 1000 -w 1000 -z 0
```
### Error
```bash
nccl-tests/build/all_reduce_perf: symbol lookup error: nccl-tests/build/all_reduce_perf: undefined symbol: ncclRedOpCreatePreMulSum
nccl-tests/build/all_reduce_perf: symbol lookup error: nccl-tests/build/all_reduce_perf: undefined symbol: ncclRedOpCreatePreMulSum
nccl-tests/build/all_reduce_perf: symbol lookup error: nccl-tests/build/all_reduce_perf: undefined symbol: ncclRedOpCreatePreMulSum
nccl-tests/build/all_reduce_perf: symbol lookup error: nccl-tests/build/all_reduce_perf: undefined symbol: ncclRedOpCreatePreMulSum
nccl-tests/build/all_reduce_perf: symbol lookup error: nccl-tests/build/all_reduce_perf: undefined symbol: ncclRedOpCreatePreMulSum
nccl-tests/build/all_reduce_perf: symbol lookup error: nccl-tests/build/all_reduce_perf: undefined symbol: ncclRedOpCreatePreMulSum
nccl-tests/build/all_reduce_perf: symbol lookup error: nccl-tests/build/all_reduce_perf: undefined symbol: ncclRedOpCreatePreMulSum
nccl-tests/build/all_reduce_perf: symbol lookup error: nccl-tests/build/all_reduce_perf: undefined symbol: ncclRedOpCreatePreMulSum
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[10610,1],0]
  Exit code:    127
--------------------------------------------------------------------------
```
### ReadMe Instructions
```
$ git clone -b lowlatency https://github.com/microsoft/msccl.git
$ cd msccl/
$ make -j src.build
$ cd ../
$ git clone https://github.com/nvidia/nccl-tests.git
$ cd nccl-tests/
$ make MPI=1 NCCL_HOME=../msccl/build/ -j 
$ cd ../
```

### `nvcc -V`

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Oct_11_21:27:02_PDT_2021
Cuda compilation tools, release 11.4, V11.4.152
Build cuda_11.4.r11.4/compiler.30521435_0
```

**Comment by sshleifer** [comment]
Removing
```-x LD_LIBRARY_PATH=msccl/build/lib/:$LD_LIBRARY_PATH -x SCCL_XML_FILES=msccl/src/xml_generator/ar_ll.xml:msccl/src/xml_generator/ar_ll128.xml
```
causes the tests to succeed on my system
### Working Baseline Command 
```
mpirun -np 8 -mca pml ob1 --mca btl ^openib -mca btl_tcp_if_exclude lo,docker0 -mca  coll_hcoll_enable 0 -x NCCL_DEBUG=INFO -x NCCL_DEBUG_SUBSYS=INIT,ENV -x NCCL_NET_SHARED_BUFFERS=0 -x NCCL_ALGO=RING,TREE -x CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 nccl-tests/build/all_reduce_perf -b 128 -e 64MB -f 2 -g 1 -c 1 -n 1000 -w 1000 -z 0
```

**Comment by saeedmaleki** [comment]
hi @sshleifer, the issue you're facing is because of API change in the newer nccl-tests. You may try [this](https://github.com/parasailteam/nccl-master/) cloned version of nccl-tests which also have the necessary changes for Alltoall collective.

If you remove LD_LIBRARY_PATH, you will be using the one installed on your system and not MSCCL.

**Comment by sshleifer** [comment]
The README of the "nccl-master" repo you linked says

> Tests for NCCL are maintained separately at https://github.com/nvidia/nccl-tests.

Did you mean to link this fork: https://github.com/parasailteam/nccl-tests ?

**Comment by saeedmaleki** [comment]
Hi @sshleifer, I couldn't reproduce your issue. I think what happened was that you compiled nccl-tests with a newer version of NCCL and then at compilation time you used MSCCL. Please see [this](https://github.com/NVIDIA/nccl-tests/blob/7130fa6096466f80b0c310b9a3070b6556c0e158/src/common.cu#L33). I just used the latest version of nccl-tests from nvidia's git repo with MSCCL and everything compiles and executes smoothly.

**Comment by jkhourybbn** [comment]
I ran into similar issues at some point when using cuda>11.4, perhaps with 11.4 or 11.1

**Comment by jkhourybbn** [comment]
@saeedmaleki I do compile with NCCL_HOME pointing to msccl and it all works well, but only with cuda<11.4 . 
Was just pointing out that at some point we saw undefined symbols (similar to this issue) and that was because of cuda 11.6.

**Comment by saeedmaleki** [comment]
@jkhourybbn, as always thanks for reporting bugs like these! CUDA 11.6 gives me the following error:
`[0] enqueue.cc:268 NCCL WARN Cuda failure invalid device function`

Which is now fixed in this [commit](https://github.com/microsoft/msccl/commit/1d3f0a4917dd415eec57cf2d95475c2441d4cd8a).

That being said, I couldn't reproduce the `undefined symbol: ncclRedOpCreatePreMulSum` issue. For me, this issue happens when nccl-tests picks up a different NCCL_HOME than MSCCL's. Can you please try `make install` in MSCCL build directory and see if the issue still occurs? If so, can you please tell me the steps to reproduce this error. Thanks!

**Comment by jkhourybbn** [comment]
@saeedmaleki tested the patch works now thanks. I think you are right I must have been linking against the wrong NCCL when getting the symbol errors.

**Comment by saeedmaleki** [comment]
OK great! Then I think this issue is resolved, I will close it. Thanks again for reporting bugs! :)
