### ISSUE TITLE
Datacheck fails only with `LL` protocol

### ISSUE THREAD

**Issue by liangyuRain** [microsoft/msccl#27]
Hi, the attached 6-node allreduce schedule fails the datacheck with `LL` protocol and at small sizes. However, the datacheck is fine when protocol is `Simple` or `LL128`.

[schedule.txt](https://github.com/microsoft/msccl/files/9043344/schedule.txt)

`LL` Output (datacheck fails at the first three sizes):
```
#
#                                                       out-of-place                       in-place          
#       size         count      type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                       (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
         192            48     float     sum    29.73    0.01    0.01  9e-02
         384            96     float     sum    28.63    0.01    0.02  5e-02
         768           192     float     sum    28.14    0.03    0.05  2e-02
        1536           384     float     sum    24.35    0.06    0.11  2e-07
        3072           768     float     sum    24.96    0.12    0.21  2e-07
        6144          1536     float     sum    27.63    0.22    0.37  2e-07
       12288          3072     float     sum    28.13    0.44    0.73  5e-07
       24576          6144     float     sum    29.04    0.85    1.41  5e-07
       49152         12288     float     sum    30.66    1.60    2.67  5e-07
       98304         24576     float     sum    33.85    2.90    4.84  5e-07
      196608         49152     float     sum    41.39    4.75    7.92  5e-07
      393216         98304     float     sum    59.40    6.62   11.03  5e-07
      786432        196608     float     sum    92.67    8.49   14.14  5e-07
     1572864        393216     float     sum    160.1    9.82   16.37  5e-07
     3145728        786432     float     sum    307.9   10.22   17.03  5e-07
     6291456       1572864     float     sum    603.1   10.43   17.39  5e-07
# Out of bounds values : 18 FAILED
# Avg bus bandwidth    : 5.89321 
#
```

`Simple` Output:
```
#
#                                                       out-of-place                       in-place          
#       size         count      type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                       (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
         192            48     float     sum    68.20    0.00    0.00  1e-07
         384            96     float     sum    68.03    0.01    0.01  1e-07
         768           192     float     sum    67.89    0.01    0.02  6e-08
        1536           384     float     sum    67.81    0.02    0.04  2e-07
        3072           768     float     sum    67.59    0.05    0.08  2e-07
        6144          1536     float     sum    64.17    0.10    0.16  2e-07
       12288          3072     float     sum    66.96    0.18    0.31  5e-07
       24576          6144     float     sum    69.75    0.35    0.59  5e-07
       49152         12288     float     sum    79.26    0.62    1.03  5e-07
       98304         24576     float     sum    79.49    1.24    2.06  5e-07
      196608         49152     float     sum    80.89    2.43    4.05  5e-07
      393216         98304     float     sum    87.15    4.51    7.52  5e-07
      786432        196608     float     sum    107.8    7.30   12.16  5e-07
     1572864        393216     float     sum    152.9   10.29   17.15  5e-07
     3145728        786432     float     sum    230.5   13.65   22.75  5e-07
     6291456       1572864     float     sum    389.0   16.17   26.96  5e-07
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 5.93026 
#
```

`LL128` Output:
```
#
#                                                       out-of-place                       in-place          
#       size         count      type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                       (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
         192            48     float     sum    54.57    0.00    0.01  1e-07
         384            96     float     sum    54.44    0.01    0.01  1e-07
         768           192     float     sum    54.44    0.01    0.02  6e-08
        1536           384     float     sum    54.54    0.03    0.05  2e-07
        3072           768     float     sum    54.48    0.06    0.09  2e-07
        6144          1536     float     sum    72.97    0.08    0.14  2e-07
       12288          3072     float     sum    72.51    0.17    0.28  5e-07
       24576          6144     float     sum    73.21    0.34    0.56  5e-07
       49152         12288     float     sum    74.69    0.66    1.10  5e-07
       98304         24576     float     sum    77.22    1.27    2.12  5e-07
      196608         49152     float     sum    82.67    2.38    3.96  5e-07
      393216         98304     float     sum    92.37    4.26    7.10  5e-07
      786432        196608     float     sum    99.20    7.93   13.21  5e-07
     1572864        393216     float     sum    137.2   11.47   19.11  5e-07
     3145728        786432     float     sum    216.0   14.57   24.28  5e-07
     6291456       1572864     float     sum    372.2   16.90   28.17  5e-07
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 6.26362 
#
```

Meanwhile, when changing the `coll` to `allgather` or `reduce_scatter`, NCCL fails to start with the following error when running `all_gather_perf` and `reduce_scatter_perf`.
```
g1lmd6:2758544:2758544 [3] enqueue.cc:346 NCCL WARN Error : no algorithm/protocol available
g1lmd6: Test NCCL failure reduce_scatter.cu:58 'internal error'
 .. g1lmd6 pid 2758544: Test failure common.cu:583
 .. g1lmd6 pid 2758544: Test failure common.cu:796
 .. g1lmd6 pid 2758544: Test failure reduce_scatter.cu:104
 .. g1lmd6 pid 2758544: Test failure common.cu:824
 .. g1lmd6 pid 2758544: Test failure common.cu:1199
 .. g1lmd6 pid 2758544: Test failure common.cu:1039
```

**Comment by liangyuRain** [comment]
It seems that the problem only occurs when `nchunksperloop` is large. I used to run into this problem with another schedule, which I cannot find right now. I have looked into the cuda memory step by step, and found that at some step half of the chunk got modified instead of the whole chunk. For example, if array[0, 1, 2, 3] correspond to a chunk, after a `re` or `r`, array[2, 3] got modified, while array[0, 1] are intact.

**Comment by saeedmaleki** [comment]
Hi @liangyuRain, I could reproduce the bug. Do you happen to have a smaller schedule.xml file we could use to debug this? Thanks!

**Comment by liangyuRain** [comment]
Here is also a 6-node ring allreduce schedule. It has exactly the same bug with `LL` fails at small sizes. The schedule has each threadblock send-only or recv-only, so it has 4 threadblocks. I guess the bug happens at large `nchunksperloop` and higher number of threadblocks.

[schedule.txt](https://github.com/microsoft/msccl/files/9049771/schedule.txt)

`LL` Output:
```
#
#                                                       out-of-place                       in-place          
#       size         count      type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                       (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
          48            12     float     sum    33.85    0.00    0.00  1e+00
          96            24     float     sum    32.82    0.00    0.00  1e+00
         192            48     float     sum    34.17    0.01    0.01  9e-01
         384            96     float     sum    33.47    0.01    0.02  3e-08
         768           192     float     sum    33.39    0.02    0.04  3e-08
        1536           384     float     sum    33.38    0.05    0.08  2e-07
        3072           768     float     sum    34.82    0.09    0.15  2e-07
        6144          1536     float     sum    38.41    0.16    0.27  2e-07
       12288          3072     float     sum    39.89    0.31    0.51  2e-07
       24576          6144     float     sum    41.66    0.59    0.98  2e-07
       49152         12288     float     sum    47.63    1.03    1.72  2e-07
       98304         24576     float     sum    59.12    1.66    2.77  2e-07
      196608         49152     float     sum    79.52    2.47    4.12  2e-07
      393216         98304     float     sum    119.2    3.30    5.50  2e-07
      786432        196608     float     sum    226.9    3.47    5.78  2e-07
     1572864        393216     float     sum    442.0    3.56    5.93  2e-07
     3145728        786432     float     sum    871.3    3.61    6.02  2e-07
     6291456       1572864     float     sum   1731.9    3.63    6.05  2e-07
# Out of bounds values : 18 FAILED
# Avg bus bandwidth    : 2.21947 
#
```

`Simple` Output:
```
#
#                                                       out-of-place                       in-place          
#       size         count      type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                       (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
          48            12     float     sum    103.2    0.00    0.00  1e-07
          96            24     float     sum    102.8    0.00    0.00  1e-07
         192            48     float     sum    102.1    0.00    0.00  3e-08
         384            96     float     sum    101.9    0.00    0.01  3e-08
         768           192     float     sum    101.5    0.01    0.01  3e-08
        1536           384     float     sum    101.0    0.02    0.03  2e-07
        3072           768     float     sum    100.8    0.03    0.05  2e-07
        6144          1536     float     sum    102.5    0.06    0.10  2e-07
       12288          3072     float     sum    107.5    0.11    0.19  2e-07
       24576          6144     float     sum    112.6    0.22    0.36  2e-07
       49152         12288     float     sum    121.7    0.40    0.67  2e-07
       98304         24576     float     sum    126.9    0.77    1.29  2e-07
      196608         49152     float     sum    143.3    1.37    2.29  2e-07
      393216         98304     float     sum    177.5    2.21    3.69  2e-07
      786432        196608     float     sum    247.9    3.17    5.29  2e-07
     1572864        393216     float     sum    374.3    4.20    7.00  2e-07
     3145728        786432     float     sum    627.8    5.01    8.35  2e-07
     6291456       1572864     float     sum   1125.3    5.59    9.32  2e-07
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 2.14765 
#
```

**Comment by saeedmaleki** [comment]
Thank you, it was a bug related to memory consistency of CUDA! Can you please try out this [branch](https://github.com/microsoft/msccl/tree/ll_load_al_fix)? I tried your 3 schedules and they all passed the test. If all look good, I will create a PR.

**Comment by liangyuRain** [comment]
I got following error with [commit](https://github.com/microsoft/msccl/commit/f7c25e0502290e27d1154ab36103db858580cc76).
```
g1lmd6: Test CUDA failure common.cu:506 'misaligned address'
 .. g1lmd6 pid 2990026: Test failure common.cu:607
 .. g1lmd6 pid 2990026: Test failure common.cu:805
 .. g1lmd6 pid 2990026: Test failure all_reduce.cu:103
 .. g1lmd6 pid 2990026: Test failure common.cu:824
 .. g1lmd6 pid 2990026: Test failure common.cu:1199
 .. g1lmd6 pid 2990026: Test failure common.cu:1039
```

**Comment by saeedmaleki** [comment]
Ah makes sense. What's your test case?

**Comment by liangyuRain** [comment]
The schedule I run is [schedule.txt](https://github.com/microsoft/msccl/files/9052489/schedule.txt). The command is
`mpirun -np 6 -x NCCL_NET_SHARED_BUFFERS=0  -x MSCCL_XML_FILES=schedule/schedule.xml -x NCCL_ALGO=MSCCL -x CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=ALL -x LD_LIBRARY_PATH=~/msccl/build/lib/:$LD_LIBRARY_PATH ~/nccl-tests/build/all_reduce_perf -b 48 -e 6M -f 2 -g 1 -c 1 -n 200 -w 200 -z 0`

**Comment by saeedmaleki** [comment]
@liangyuRain , do you have a 2 GPU or 3 GPU version of your schedule which gives the incorrect result with `LL` for small sizes?

**Comment by liangyuRain** [comment]
Here is a 3-node ring allreduce schedule.

[schedule.txt](https://github.com/microsoft/msccl/files/9057917/schedule.txt)

**Comment by saeedmaleki** [comment]
hi @liangyuRain, I believe the issue is resolved in branch ll_load_al_fix, however, it is not a performant fix. Can you please confirm you also get correct results? We will work on a more performant solution.

**Comment by liangyuRain** [comment]
Thanks, I will test a bunch of schedules. However, I do notice the other bug is unsolved. While the 3-node ring allreduce schedule can be run at size `24B`, if I change the schedule to `coll="reduce_scatter"` and run with `reduce_scatter_perf`. The following error is reported:
```
g1lmd6:3343022:3343022 [2] enqueue.cc:346 NCCL WARN Error : no algorithm/protocol available
g1lmd6: Test NCCL failure all_gather.cu:59 'internal error'
 .. g1lmd6 pid 3343022: Test failure common.cu:583
 .. g1lmd6 pid 3343022: Test failure common.cu:796
 .. g1lmd6 pid 3343022: Test failure all_gather.cu:93
 .. g1lmd6 pid 3343022: Test failure common.cu:824
 .. g1lmd6 pid 3343022: Test failure common.cu:1199
 .. g1lmd6 pid 3343022: Test failure common.cu:1039
```
Only if I increase the `minBytes` to `72B` (`nchunksperloop * sizeof(float) * ngpus`), the schedule can be successfully run by `reduce_scatter_perf`.

**Comment by saeedmaleki** [comment]
Try again in the same branch :)

**Comment by liangyuRain** [comment]
It works. Thx!

**Comment by saeedmaleki** [comment]
still working on fixing the readAL in a proper way that doesn't slow down the `re` ops.

**Comment by saeedmaleki** [comment]
@liangyuRain, use branch `merging_with_nccl` for now until this branch is merged into master. It should have all of the correctness and performance issues fixed.

**Comment by saeedmaleki** [comment]
this is fixed in master now.
